/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectsImport } from './routes/projects/$projects'
import { Route as PostPostImport } from './routes/post/$post'
import { Route as BoardBoardImport } from './routes/board/$board'
import { Route as BacklogBacklogImport } from './routes/backlog/$backlog'
import { Route as BoardTaskTaskIdImport } from './routes/board/task/$taskId'
import { Route as ProjectsProjectsIdProjectsIdImport } from './routes/projects/projects-id/projectsId'
import { Route as BoardTaskTaskIdImport } from './routes/board/task/$taskId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsRoute = ProjectsProjectsImport.update({
  id: '/projects/$projects',
  path: '/projects/$projects',
  getParentRoute: () => rootRoute,
} as any)

const PostPostRoute = PostPostImport.update({
  id: '/post/$post',
  path: '/post/$post',
  getParentRoute: () => rootRoute,
} as any)

const BoardBoardRoute = BoardBoardImport.update({
  id: '/board/$board',
  path: '/board/$board',
  getParentRoute: () => rootRoute,
} as any)

const BacklogBacklogRoute = BacklogBacklogImport.update({
  id: '/backlog/$backlog',
  path: '/backlog/$backlog',
  getParentRoute: () => rootRoute,
} as any)

const BoardTaskTaskIdRoute = BoardTaskTaskIdImport.update({
  id: '/board/task/$taskId',
  path: '/board/task/$taskId',
  getParentRoute: () => rootRoute,
} as any)
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsIdProjectsIdRoute =
  ProjectsProjectsIdProjectsIdImport.update({
    id: '/projects/projects-id/projectsId',
    path: '/projects/projects-id/projectsId',
    getParentRoute: () => rootRoute,
  } as any)

const BoardTaskTaskIdRoute = BoardTaskTaskIdImport.update({
  id: '/board/task/$taskId',
  path: '/board/task/$taskId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/backlog/$backlog': {
      id: '/backlog/$backlog'
      path: '/backlog/$backlog'
      fullPath: '/backlog/$backlog'
      preLoaderRoute: typeof BacklogBacklogImport
      parentRoute: typeof rootRoute
    }
    '/board/$board': {
      id: '/board/$board'
      path: '/board/$board'
      fullPath: '/board/$board'
      preLoaderRoute: typeof BoardBoardImport
      parentRoute: typeof rootRoute
    }
    '/post/$post': {
      id: '/post/$post'
      path: '/post/$post'
      fullPath: '/post/$post'
      preLoaderRoute: typeof PostPostImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projects': {
      id: '/projects/$projects'
      path: '/projects/$projects'
      fullPath: '/projects/$projects'
      preLoaderRoute: typeof ProjectsProjectsImport
      parentRoute: typeof rootRoute
    }
    '/board/task/$taskId': {
      id: '/board/task/$taskId'
      path: '/board/task/$taskId'
      fullPath: '/board/task/$taskId'
      preLoaderRoute: typeof BoardTaskTaskIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/projects-id/projectsId': {
      id: '/projects/projects-id/projectsId'
      path: '/projects/projects-id/projectsId'
      fullPath: '/projects/projects-id/projectsId'
      preLoaderRoute: typeof ProjectsProjectsIdProjectsIdImport
      parentRoute: typeof rootRoute
    }
    '/board/task/$taskId': {
      id: '/board/task/$taskId'
      path: '/board/task/$taskId'
      fullPath: '/board/task/$taskId'
      preLoaderRoute: typeof BoardTaskTaskIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/board/$board': typeof BoardBoardRoute
  '/post/$post': typeof PostPostRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/board/task/$taskId': typeof BoardTaskTaskIdRoute
  '/projects/projects-id/projectsId': typeof ProjectsProjectsIdProjectsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/board/$board': typeof BoardBoardRoute
  '/post/$post': typeof PostPostRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/board/task/$taskId': typeof BoardTaskTaskIdRoute
  '/projects/projects-id/projectsId': typeof ProjectsProjectsIdProjectsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/board/$board': typeof BoardBoardRoute
  '/post/$post': typeof PostPostRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/$projectsId': typeof ProjectsProjectsIdRoute
  '/board/task/$taskId': typeof BoardTaskTaskIdRoute
  '/projects/projects-id/projectsId': typeof ProjectsProjectsIdProjectsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/board/$board'
    | '/post/$post'
    | '/projects/$projects'
    | '/projects/$projectsId'
    | '/board/task/$taskId'
    | '/projects/projects-id/projectsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/board/$board'
    | '/post/$post'
    | '/projects/$projects'
    | '/projects/$projectsId'
    | '/board/task/$taskId'
    | '/projects/projects-id/projectsId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/board/$board'
    | '/post/$post'
    | '/projects/$projects'
    | '/projects/$projectsId'
    | '/board/task/$taskId'
    | '/projects/projects-id/projectsId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacklogBacklogRoute: typeof BacklogBacklogRoute
  BoardBoardRoute: typeof BoardBoardRoute
  PostPostRoute: typeof PostPostRoute
  ProjectsProjectsRoute: typeof ProjectsProjectsRoute
  ProjectsProjectsIdRoute: typeof ProjectsProjectsIdRoute
  BoardTaskTaskIdRoute: typeof BoardTaskTaskIdRoute
  ProjectsProjectsIdProjectsIdRoute: typeof ProjectsProjectsIdProjectsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacklogBacklogRoute: BacklogBacklogRoute,
  BoardBoardRoute: BoardBoardRoute,
  PostPostRoute: PostPostRoute,
  ProjectsProjectsRoute: ProjectsProjectsRoute,
  ProjectsProjectsIdRoute: ProjectsProjectsIdRoute,
  BoardTaskTaskIdRoute: BoardTaskTaskIdRoute,
  ProjectsProjectsIdProjectsIdRoute: ProjectsProjectsIdProjectsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/backlog/$backlog",
        "/board/$board",
        "/post/$post",
        "/projects/$projects",
        "/projects/$projectsId",
        "/board/task/$taskId"
        "/projects/projects-id/projectsId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/backlog/$backlog": {
      "filePath": "backlog/$backlog.jsx"
    },
    "/board/$board": {
      "filePath": "board/$board.jsx"
    },
    "/post/$post": {
      "filePath": "post/$post.jsx"
    },
    "/projects/$projects": {
      "filePath": "projects/$projects.jsx"
    },
    "/projects/$projectsId": {
      "filePath": "projects/$projectsId.jsx"
    },
    "/board/task/$taskId": {
      "filePath": "board/task/$taskId.jsx"
    "/projects/projects-id/projectsId": {
      "filePath": "projects/projects-id/projectsId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
