/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectsImport } from './routes/projects/$projects'
import { Route as BacklogBacklogImport } from './routes/backlog/$backlog'
import { Route as ProjectsProjectsIdProjecstTitleImport } from './routes/projects/projects-id/$projecstTitle'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsRoute = ProjectsProjectsImport.update({
  id: '/projects/$projects',
  path: '/projects/$projects',
  getParentRoute: () => rootRoute,
} as any)

const BacklogBacklogRoute = BacklogBacklogImport.update({
  id: '/backlog/$backlog',
  path: '/backlog/$backlog',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsIdProjecstTitleRoute =
  ProjectsProjectsIdProjecstTitleImport.update({
    id: '/projects/projects-id/$projecstTitle',
    path: '/projects/projects-id/$projecstTitle',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/backlog/$backlog': {
      id: '/backlog/$backlog'
      path: '/backlog/$backlog'
      fullPath: '/backlog/$backlog'
      preLoaderRoute: typeof BacklogBacklogImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projects': {
      id: '/projects/$projects'
      path: '/projects/$projects'
      fullPath: '/projects/$projects'
      preLoaderRoute: typeof ProjectsProjectsImport
      parentRoute: typeof rootRoute
    }
    '/projects/projects-id/$projecstTitle': {
      id: '/projects/projects-id/$projecstTitle'
      path: '/projects/projects-id/$projecstTitle'
      fullPath: '/projects/projects-id/$projecstTitle'
      preLoaderRoute: typeof ProjectsProjectsIdProjecstTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/projects-id/$projecstTitle': typeof ProjectsProjectsIdProjecstTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/projects-id/$projecstTitle': typeof ProjectsProjectsIdProjecstTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog/$backlog': typeof BacklogBacklogRoute
  '/projects/$projects': typeof ProjectsProjectsRoute
  '/projects/projects-id/$projecstTitle': typeof ProjectsProjectsIdProjecstTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/projects/$projects'
    | '/projects/projects-id/$projecstTitle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/projects/$projects'
    | '/projects/projects-id/$projecstTitle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backlog/$backlog'
    | '/projects/$projects'
    | '/projects/projects-id/$projecstTitle'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacklogBacklogRoute: typeof BacklogBacklogRoute
  ProjectsProjectsRoute: typeof ProjectsProjectsRoute
  ProjectsProjectsIdProjecstTitleRoute: typeof ProjectsProjectsIdProjecstTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacklogBacklogRoute: BacklogBacklogRoute,
  ProjectsProjectsRoute: ProjectsProjectsRoute,
  ProjectsProjectsIdProjecstTitleRoute: ProjectsProjectsIdProjecstTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/backlog/$backlog",
        "/projects/$projects",
        "/projects/projects-id/$projecstTitle"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/backlog/$backlog": {
      "filePath": "backlog/$backlog.jsx"
    },
    "/projects/$projects": {
      "filePath": "projects/$projects.jsx"
    },
    "/projects/projects-id/$projecstTitle": {
      "filePath": "projects/projects-id/$projecstTitle.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
